version: 1
disable_existing_loggers: true
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: WARNING
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: verbose
    level: DEBUG
    filename: default.log
    backupCount: 5
    maxBytes: 1024000
  console_debug:
    class: logging.StreamHandler
    formatter: verbose
    level: DEBUG
formatters:
  brief:
    format: '[%(levelname)-8s] %(message)s'
  verbose:
    format: '%(asctime)s [%(levelname)-8s] %(name)-10s: %(message)s || %(filename)s:%(lineno)d:%(funcName)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
loggers:
  default:
    level: DEBUG
    handlers:
      - console
      - file
